USE [TEST]
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Anagrafica](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Anagrafica] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET IDENTITY_INSERT [dbo].[Anagrafica] ON 
GO
INSERT [dbo].[Anagrafica] ([ID], [Nome]) VALUES (1, N'Giorgio')
GO
SET IDENTITY_INSERT [dbo].[Anagrafica] OFF
GO
